### ISSUE TITLE
Pushing data to Elasticsearch causes number format exception in Stock SMS example

### ISSUE THREAD

**Issue by miklosduma** [sparkl/cli#21]
```
yev-sparkl:~ miklosduma$ sparkl listen -c Demos/Logger | sparkl elastic -c 1
Existing index sparkl
Websocket opened on wss://saas.sparkl.com/svc_rest/websocket/Demos/Logger
Traceback (most recent call last):
  File "/usr/local/bin/sparkl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sparkl_cli/main.py", line 159, in main
    args.fun()
  File "/usr/local/lib/python2.7/site-packages/sparkl_cli/cmd_elastic.py", line 80, in command
    for (ok, result) in stream:
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 163, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 135, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'data_event', u'_id': u'N-JY6-ROF-2PJ4', u'error': {u'caused_by': {u'reason': u'For input string: "nasdaq:aapl"', u'type': u'number_format_exception'}, u'reason': u'failed to parse [data.value]', u'type': u'mapper_parsing_exception'}, u'_index': u'sparkl'}}])
ERROR:websocket:error from callback <bound method CliWebsocket.__ws_message of <sparkl_cli.CliWebsocket.CliWebsocket object at 0x105b62350>>: exception: Exception <type 'exceptions.IOError'>: [Errno 32] Broken pipe
Call: Log
Data: {u'event': u'{"tag":"evm_event","attr":{"source":"dispatcher","subject":"L-JY6-ROF-4A","timestamp":1496657191946},"content":[{"tag":"cause","attr":{},"content":[{"tag":"cause","attr":{"event_type":"data_event","subject_type":"request","subject":"K-JY6-ROF-48","repeat":0,"event":"N-JY6-ROF-2PKG","subject_path":"demo@sparkl.com/Demos/StockSMS/Mix/SendMessage"}},{"tag":"cause","attr":{"event_type":"txn_start_event","subject_type":"service","subject":"F-JY6-ROF-3C","repeat":0,"event":"T-JY6-ROF-2PJ8","subject_path":"demo@sparkl.com/Demos/StockSMS/Sequencer"}},{"tag":"cause","attr":{"event_type":"data_event","subject_type":"solicit","subject":"I-JY6-ROF-3W","repeat":0,"event":"N-JY6-ROF-2PJ4","subject_path":"demo@sparkl.com/Demos/StockSMS/Mix/Solicit"}},{"tag":"cause","attr":{"event_type":"root_cause","subject_type":"user","subject":"G-JY6-ROF-30","subject_path":"demo@sparkl.com"}}]},{"tag":"data_event","attr":{"id":"N-JY6-ROF-2PLE","subject":"L-JY6-ROF-4A","ref":"N-JY6-ROF-2PKG","txn":"T-JY6-ROF-2PJ8"},"content":[{"tag":"datum","attr":{"field":"B-JY6-ROF-3U"}}]}]}'}

Websocket closed on wss://saas.sparkl.com/svc_rest/websocket/Demos/Logger
```

**Comment by jacobythwaites** [comment]
Fixed by #25
