### ISSUE TITLE
sparkl service without previous login fails

### ISSUE THREAD

**Issue by jacobythwaites** [sparkl/cli#60]
This error occurs when you don't have an ipaas_session cookie (even an invalid one) when connecting to a REST service whose permission for `*` users is `x`.
```
jthwaites data $ sparkl service admin@sparkl.com/Scratch/Primes/REST test_rest
Traceback (most recent call last):
  File "/usr/local/bin/sparkl", line 11, in <module>
    load_entry_point('sparkl-cli==1.3.1', 'console_scripts', 'sparkl')()
  File "/usr/local/lib/python2.7/site-packages/sparkl_cli/main.py", line 242, in main
    result = args.fun(args)
  File "/usr/local/lib/python2.7/site-packages/sparkl_cli/cmd_service.py", line 52, in command
    service = Service(args, module)
  File "/usr/local/lib/python2.7/site-packages/sparkl_cli/Service.py", line 53, in __init__
    self.__open(args)
  File "/usr/local/lib/python2.7/site-packages/sparkl_cli/Service.py", line 79, in __open
    session = cookiedict[SESSION_COOKIE]
KeyError: 'ipaas_session'
```

**Comment by jacobythwaites** [comment]
Fixed
